name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Load .env.dev
        run: |
          set -o allexport; source .env.dev; set +o allexport

      - name: Run unit tests
        run: uv run pytest tests -v -m "not integration"

      - name: Run docker services
        if: github.ref == 'refs/heads/main'
        run: docker compose --env-file .env.dev up -d

      - name: Wait for Postgres to be ready
        if: github.ref == 'refs/heads/main'
        run: scripts/wait-for-it.sh -t 30 -s localhost:5432 -- echo "Postgres is up!"

      - name: Run migrations
        if: github.ref == 'refs/heads/main'
        run: uv run alembic upgrade head

      - name: Run integration tests
        if: github.ref == 'refs/heads/main'
        run: uv run pytest tests -v -m "integration"
